PRESS4-300 analytics data
newfold-labs/wp-module-data pull request #28
Opened 2023-09-08 06:56 UTC by sumathi3399

JIRA ticket:- https://jira.newfold.com/browse/PRESS4-300

Event logs for sending the data to Google analytics through hive

2023-09-08 13:05 UTC, wpscholar requested changes

2023-09-08 13:05 UTC, wpscholar commented on src/Listeners/Yith.php
> +		$_SERVER['HTTPS'] === 'on' ? "https://" : "http://";
We should use the `is_ssl()` in all places where we're currently doing this code. The WordPress function has more robust checks for SSL.

https://developer.wordpress.org/reference/functions/is_ssl/

2023-09-12 15:49 UTC, wpscholar approved these changes

2023-09-12 16:05 UTC, circlecube approved these changes

2023-09-12 18:13 UTC, merged